#!/bin/bash
#
#
# Usage: $0 <list>
# Parse build.sync file format and outputs the dependency list information only
#
if [ $# -eq 0 ]; then
  echo "Usage: $0 <list>"
  exit 1
fi
#check if file exists
if [ ! -r $1 ]; then
  echo "error: file ${1} does not exist"
  exit 1
fi
#Read file and preprocess all relevant info. discard everything else.
while read line
  do 
    #trim comments
    cline=$(echo "$line" | sed -e "s/[ \t]*#.*//g")
    if [[ -n  $cline ]]; then
      echo "$(echo $cline | cut -d ' ' -f1) $(echo $cline | cut -d ' ' -f2)"
    fi
done < "$1"
