#!/bin/bash
#
#
# Usage: $0 <list>
#Makes several git-checkout from each repository in <list> file
#return value: 0: only versioned dependencies listed
#              1: contains non-versioned dependency
#
if [ $# -eq 0 ]; then
  echo "Usage: $0 <list>"
  exit 1
fi
#Note: This scripts assumes that BSYNCDIR variable exists and is a valid path
#check if file exists
if [ ! -r $1 ]; then
  echo "error: file ${1} does not exist"
fi

#Read file and checkout each repository
volatile=0
while read line;do
  read repo version <<<$(echo "$line")
  if test "$version" != "local"; then
    git -C $repo checkout $version
  else
    volatile=1
  fi
done < "$1"
echo "$volatile"
exit 0
